# @package _global_

defaults:
  - default

trainer:
  barebones: true # Runs n if set to n (int) else 1 if set to True batch(es) of train, val and test to find any bugs (ie: a sort of unit test).

callbacks: null
logger: null
