# @package _global_

# runs 1 train, 1 validation and 1 test step

defaults:
  - default

trainer:
  fast_dev_run: true # Runs n if set to n (int) else 1 if set to True batch(es) of train, val and test to find any bugs (ie: a sort of unit test).

callbacks: null
loggers: null
