# @package _global_

# How much of dataset to check. Adapt to your devices. limit_*_batches is a global batch subset split across devices.

defaults:
  - default

trainer:
  limit_train_batches: 0.01 # uses only 1% of the training data
  limit_val_batches: 0.05 # uses only 5% of validation data
  limit_test_batches: 0.05 # uses only 5% of test data

callbacks: null
logger: null
