# @package _global_

defaults:
  - default

trainer:
  max_epochs: 1000
  overfit_batches: 1 # Number of batches to overfit to.

# model ckpt and early stopping need to be disabled during overfitting
callbacks: null
