# @package _global_

defaults:
  - override /hydra/sweeper: optuna
# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
hydra: # docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null
    # name of the study to persist optimization results
    study_name: null
    n_jobs: 1 # # number of parallel workers. Default: 1
    direction: maximize # 'minimize' or 'maximize' the objective
    n_trials: 1 # total number of runs that will be executed
    sampler: # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
      _target_: optuna.samplers.TPESampler
      seed: ${seed}
      n_startup_trials: 10 # number of random sampling runs before optimization starts
    # define hyperparameter search space
    params: ???
