# @package module

# https://lightning.ai/docs/torchmetrics/stable/classification/f1_score.html

metric:
  _target_: torchmetrics.MulticlassFBetaScore
  beta: 1
  task: multiclass
  num_classes: ??
  average: macro
  multidim_average: global
  top_k: 1
  ignore_index: null
  validate_args: true
  zero_division: 0.0
  compute_on_cpu: true
  dist_sync_on_step: false
  dist_sync_fn: null
  distributed_available_fn: null
  sync_on_compute: true
  compute_with_cache: true
