datamodule:
  _target_: radiocovid.core.RadioCovidDataModule

  dataset:
    _target_: radiocovid.core.RadioCovidDataset

  train_loader:
    _partial_: true
    _target_: torch.utils.data.DataLoader
    batch_size: 25
    persistent_workers: true
    pin_memory: false
    num_workers: 2
    shuffle: false
    drop_last: true
    prefetch_factor: 2

  eval_loader:
    _partial_: true
    _target_: torch.utils.data.DataLoader
    batch_size: 25
    persistent_workers: true
    pin_memory: false
    num_workers: 2
    shuffle: false
    drop_last: true
    prefetch_factor: 2
  seed: "${seed}"
