# https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.loggers.wandb.html. for more options.

wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  save_dir: ??? # Path where data is saved
  offline: False # Run offline (data can be streamed later to wandb servers)
  id: null # pass correct id to resume experiment!
  anonymous: null # enable anonymous logging
  project: ??? # The name of the project to which this run will belong. WANDB_PROJECT will be used as a fallback.
  log_model: False # Log checkpoints created by ModelCheckpoint. latest and best aliases are automatically set.
  # if log_model == 'all', checkpoints are logged during training.
  # if log_model == True, checkpoints are logged at the end of training, except when save_top_k == -1 which also logs every checkpoint during training.
  # if log_model == False (default), no checkpoint is logged.
  entity: ??? # set to name of your wandb team
  group: "" # TODO: master how use it for TPU
  tags: ${tags}
  job_type: ${stage}
