# @package _global_

defaults:
  - module: default
  - module/loss: focal_loss
  - module/scheduler: sequential
  - module/metric: null
  - module/optimizer: adam
  - datamodule
  - trainer
  - strategy: auto
  - loggers: multiple
  - callbacks: multiple
  - paths
  - extras
  - hydra: default
  - experiment: base
  - tuner: null
  - debug: null
  - profiler: null
  - _self_

determinism:
  _target_: radiocovid.models.utils.set_seed
  seed: ${seed}
  cudnn_backend: false
  use_deterministic_algorithms: false
  warn_only: true

optimized_metric: score
seed: 4294967295
stage: train # train, eval
tags: ["dev"]
train: true
test: true
ckpt_path: null
